### ISSUE TITLE
получение полей

### ISSUE THREAD

**Issue by randomSymbol** [andrey-tech/amocrm-api-php#1]
Приветствую! есть ли более короткий способ получить кастомное поле или номер телефона без конструкции $contact = new AmoContact()->fillById->getPhone()?

**Comment by andrey-tech** [comment]
Приветствую!
$contact = new AmoContact() -> fillById() -> getPhone() - это самый короткий способ получить первый номер телефона  контакта.
$contact = new AmoContact() -> fillById() -> getCustomFieldValueById() - это самый короткий способ получить значение дополнительного поля контакта по ID поля.

**Comment by randomSymbol** [comment]
> Приветствую!
> $contact = new AmoContact() -> fillById() -> getPhone() - это самый короткий способ получить первый номер телефона контакта.
> $contact = new AmoContact() -> fillById() -> getCustomFieldValueById() - это самый короткий способ получить значение дополнительного поля контакта по ID поля.

благодарю, не могу разобраться как работать с неразобранным, как бы не пытался подключить(даже напрямую) пишет 'Fatal error: Uncaught Error: Class 'App\Integrations\API\AmoCRM\AmoIncomingLeadForm' not found ', есть какой то пример как запушить неразобранное?

**Comment by andrey-tech** [comment]
> благодарю, не могу разобраться как работать с неразобранным, как бы не пытался подключить(даже напрямую) пишет 'Fatal error: Uncaught Error: Class 'App\Integrations\API\AmoCRM\AmoIncomingLeadForm' not found ', есть какой то пример как запушить неразобранное?
Обновитесь до v2.11.2. Там этот баг исправлен.
