### ISSUE TITLE
В неразобранное не добавляются контактные данные 

### ISSUE THREAD

**Issue by joidru** [andrey-tech/amocrm-api-php#10]
Здравствуйте, обертка удобная, но вот что то не получается добавить заявку с контактами в неразобранное

    $contact = new AmoContact([
       'name' => 'Ганс-Дитрих Геншер'
    ]);
    $contact->setCustomFields([
        255114 => [[  <- тут я указываю ID поля телефона из своей CRM
            'value' => '+10349654820',
            'enum'  => 'WORK'
        ]],
        255116 => [[ <- тут я указываю ID поля почты из своей CRM
            'value' => 'hans@example.com',
            'enum'  => 'WORK'
       ]]
    ]);

Добавляется только имя. 
Я посмотрел документацию о неразобранных, и там массив отличается от того что передается в вашей обертке:
```
Так в вашей обертке
"custom_fields": [
    {
        "id": 255114,
        "values": [
            {
            'value' => '+10349654820',
            'enum'  => 'WORK'
            }
        ]
    }
]

Так в документации:
"custom_fields_values": [
    {
        "field_code": "PHONE",
        "values": [
            {
            'value' => '+10349654820',
            'enum'  => 'WORK'
            }
        ]
    }
]
```
Пробовал привести массив из обертки в соответствии с докой Амо, но все равно что то не передается.

**Comment by andrey-tech** [comment]
Добрый день!

Приведите фрагмент кода от создания новой заявки в неразобранном и вплоть до сохранения заявки, чтобы можно было воспроизвести данную ситуацию.

**Comment by joidru** [comment]
Я ваш пример использовал, ничего нового не придумывал
`
use AmoCRM\{AmoAPI, AmoLead, AmoContact, AmoIncomingLeadForm, AmoAPIException};
use AmoCRM\TokenStorage\TokenStorageException;

try {

    // Авторизация
    $subdomain = 'test';
    AmoAPI::oAuth2($subdomain);

    // Создаем новую заявку в неразобранном при добавлении из веб-формы
    $incomingLead = new AmoIncomingLeadForm();

    // Устанавливаем обязательные параметры 
    $incomingLead->setIncomingLeadInfo([
        'form_id'   => 1,
        'form_page' => 'http://dev.test.ru/',
        'form_name' => 'Страница заявки'
    ]);

    // Добавляем параметры сделки
    $lead = new AmoLead([
        'name' => 'Новая заявка с сайта'
    ]);

    $lead->setCustomFields([ 21586465 => '#1543252' ]);

    $incomingLead->addIncomingLead($lead);
     
    // Добавляем параметры контакта
    $contact = new AmoContact([
       'name' => 'Сергей Петров'
    ]);

    $contact->setCustomFields([
        159889 => [[
            'value' => '+7000000000',
         
        ]],
        159901 => [[
            'value' => 'test@test.ru',
           
       ]]
    ]);

    $incomingLead->addIncomingContact($contact);

    // Добавляем параметры компании
    $incomingLead->addIncomingCompany([
        'name' => 'ООО Петров и Ко'
    ]);

    // Сохраняем заявку
    $result = $incomingLead->save();




} catch (AmoAPIException $e) {
    printf('Ошибка (%d): %s' . PHP_EOL, $e->getCode(), $e->getMessage());
}
`

**Comment by joidru** [comment]
в амо новой аккаунт, настроек там ни каких не делал кроме создания интеграции, тариф пробный без ограничений.

**Comment by andrey-tech** [comment]
В примере опечатка, а [методы для сохранения заявки в неразобранное](https://github.com/andrey-tech/amocrm-api-php#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B5%D1%80%D0%B0%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE) описаны верно.

Сохранение заявки в неразобранное:
```php
    // Сохраняем заявку
    $result = AmoAPI::saveIncomingObjects($incomingLead);
```

**Comment by andrey-tech** [comment]
Опечатка в документации исправлена.
