### ISSUE TITLE
unlink

### ISSUE THREAD

**Issue by spiritwebdev** [andrey-tech/amocrm-api-php#11]
а метода unlink нету? Чтоб отвязывать к примеру контакты от сделок

**Comment by andrey-tech** [comment]
Метод `unlink` в настоящее время не реализован в связи с низкой востребованностью.

**Comment by spiritwebdev** [comment]
грустно, как раз востребовался( хоть библиотеку меняй теперь ради нее

**Comment by andrey-tech** [comment]
В ветке `Unlink` в класс для работы со сделками `AmoLead` [добавлено](https://github.com/andrey-tech/amocrm-api-php/commit/5cf264f1b7ae414aeebd777ff2cee3a4bbab9665) 2 новых метода:

- `removeContacts(array|int $contactIds): AmoLead` - отвязывает контакт(ы) от сделки по ID контакта(ов);
- `removeCompany(int $companyId): AmoLead` - отвязывает компанию от сделки по ID компании.

Проверяйте.

**Comment by spiritwebdev** [comment]
Спасибо огромное!)
Я временно успел хардкором через request сделать, очень не хотелось на официальную либу переходить, она не очень по сравнению с вашей.

**Comment by andrey-tech** [comment]
Новые методы добавлены в релиз [2.17.0](https://github.com/andrey-tech/amocrm-api-php/releases/tag/2.17.0).
