### ISSUE TITLE
unlink catalog elements from lead

### ISSUE THREAD

**Issue by gr1ng0wf** [andrey-tech/amocrm-api-php#12]
Как я могу произвести удаление товаров из сделки? На данный момент не могу найти нужный метод для реализации, но подобные методы появились для link и unlink контактов и компаний.

**Comment by andrey-tech** [comment]
В официальной документации по работе со [сделками](https://htmlpreview.github.io/?https://github.com/andrey-tech/amocrm-api-v2-docs/blob/master/docs/leads.html) API v2 amoCRM отсутствуют методы для удаления элементов списков (каталогов) из сделки.

**Comment by gr1ng0wf** [comment]
Отправлять запрос на обновление сделки с использованием метода `setCatalogElements([])` не помогло. В результате я просто сделал проверку на изменение в списке товаров сделке и изменения требующие unlink прогнал через `AmoAPI::request("/api/v4/{$type}/{$id}/unlink", 'POST', $params);`. А в документации для старой версии действительно нет такого функционала. Ранее пользовался другой библиотекой и там была поддержка unlink, но она старая и не поддерживает oAuth2.

**Comment by andrey-tech** [comment]
А официальная PHP-библиотека amoCRM для нового API v4 почему вам не подошла?

**Comment by gr1ng0wf** [comment]
> А официальная PHP-библиотека amoCRM для нового API v4 почему вам не подошла?

Ваша библиотека показалась более продуманной и верной :) Не хотелось писать с 0 концепт моделей, ограничений на запросы и тд.

**Comment by andrey-tech** [comment]
В отсутствии возможности удаления элементов списков из сделки с помощью API **v2** amoCRM закрываю issue.
