### ISSUE TITLE
Файлы в примечание

### ISSUE THREAD

**Issue by dmitryIG** [andrey-tech/amocrm-api-php#13]
Доброго времени суток, можно ли с вашей оберткой закинуть файл в примечание? Спасибо!

**Comment by andrey-tech** [comment]
Добрый день!

Уточните о каком методе API v2 AmoCRM идет речь.

**Comment by dmitryIG** [comment]
/api/v2/notes видимо этот, можно ли как-то в примечание файл добавить или на v2 не было такой возможности?
Через амо выглядит так добавление - https://prnt.sc/xt9nRmbwbZO2

**Comment by andrey-tech** [comment]
Необходимый вам тип примечания `attachment` не поддерживается [API v2 AmoCRM](https://htmlpreview.github.io/?https://github.com/andrey-tech/amocrm-api-v2-docs/blob/master/docs/notes.html).

**Comment by dmitryIG** [comment]
А в v4 он есть? Подскажите пожалуйста метод.

**Comment by andrey-tech** [comment]
Есть. Посмотрите в разделе [События и Примечания](https://www.amocrm.ru/developers/content/crm_platform/events-and-notes#notes-common-info) официальной документации API v4 AmoCRM.

**Comment by dmitryIG** [comment]
https://github.com/amocrm/amocrm-api-php/issues/216 тут чекнул, год назад через api не было возможности добавить. Посмотрел по вашей ссылке типы примечаний, attachment нет.

**Comment by andrey-tech** [comment]
Поищите на странице по моей ссылке пример ответа от API с `"note_type": "attachment"`. Попробуйте проверить - может быть нужный вам тип примечания `attachment` уже работает.

**Comment by dmitryIG** [comment]
Для всех интересующихся - это невозможно на текущем api.
