### ISSUE TITLE
Место хранения токена

### ISSUE THREAD

**Issue by alexloparev** [andrey-tech/amocrm-api-php#14]
Здравствуйте, а можно все-таки задать место хранения токенов AmoCRM? А то в методе __construct() если задашь $storageFolder каталог создается, правда относительно текущего места хранения, но токен все-равно сохраняется по-умолчанию в старое место.

**Comment by andrey-tech** [comment]
Добрый день!
Приведите пример кода, чтобы лучше понимать что происходит.

**Comment by andrey-tech** [comment]
Попробуйте релиз [2.17.2](https://github.com/andrey-tech/amocrm-api-php/releases/tag/2.17.2).

**Comment by andrey-tech** [comment]
В отсутствие, в разумные сроки, обратной связи, закрываю данный issue.
