### ISSUE TITLE
Примечание в неразобранном

### ISSUE THREAD

**Issue by dmitryIG** [andrey-tech/amocrm-api-php#16]
Добрый день.
Подскажите, можно ли прикрутить к неразобранному `AmoIncomingLead` примечание `AmoNote`? Пока вижу, что примечание создается с id контакта или сделки, но в неразобранном этого нет.
Спасибо.

**Comment by andrey-tech** [comment]
Добрый день.

Нет. Нельзя.

> Изначально неразобранное было в отдельном хранилище и являлось отдельной сущностью именно поэтому до сих пор в интерфейсах amoCRM и в API есть особенности которые отличают поведение сделки в статусе Неразобранное от сделок в других статусах.

**Comment by dmitryIG** [comment]
Понял, спасибо!
