### ISSUE TITLE
Ошибка при выполнении AmoAPI::request /api/v4

### ISSUE THREAD

**Issue by instocky** [andrey-tech/amocrm-api-php#17]
Здравствуйте, 
Создаю два запроса  **AmoAPI::request**
1. создание поля список в карточке сделки
2. создание вкладки в карточке сделки и перемещение созданного поля список в эту вкладку

```
use AmoCRM\{AmoAPI, AmoAPIException};
try {
    // Авторизация
    $subdomain = '***';
    AmoAPI::oAuth2($subdomain);

    $field = [
        [
            "name" => 'Field_doc',
            "type" => 'select',
            "sort" => 100,
            'enums' => [
                [
                    "value" => "КП_802",
                    "sort" => 1
                ],
                [
                    "value" => "КП_668",
                    "sort" => 2
                ],
            ]
        ]
    ];
    $fields = AmoAPI::request('/api/v4/leads/custom_fields', 'POST', $field);

    $array = [
        [
            "name" => 'TAB12',
            "sort" => 4,
            'fields' => [
                $fields['_embedded']['custom_fields'][0]['id']
            ]
        ]
    ];

    $data = AmoAPI::request('/api/v4/leads/custom_fields/groups', 'POST', $array);

    p($data);
} catch (AmoAPIException $e) {
    printf('Ошибка (%d): %s' . PHP_EOL, $e->getCode(), $e->getMessage());
}
```

скрипт отрабатывает - и вкладка и поле в нем создаются, но выдается ошибка
```
Ошибка (201): AmoCRM API: Ошибка 201 Добавление контактов: пустой массив: (POST: https://vlutin.amocrm.ru/api/v4/leads/custom_fields/groups [{"name":"TAB12","sort":4,"fields":[665587]}]) (Response: {"_total_items":1,"_embedded":{"custom_field_groups":[{"id":"leads_80401655045229","name":"TAB12","is_predefined":false,"type":"custom_field_group","fields":[665587],"entity_type":"leads","sort":3,"request_id":"0","_links":{"self":{"href":"https://vlutin.amocrm.ru/api/v4/leads/custom_fields/groups/leads_80401655045229"}}}]}})
``` 

При запросах через CURL ошибок не возникало. Подскажите пожалуйста - в какую сторону копать?

**Comment by andrey-tech** [comment]
Здравствуйте!

1. Данная библиотека предназначена для работы с REST API amoCRM **v2**, на что четко указано в её описании. Она никогда не тестировалась на запросах к API **v4**. 
2. Для нового API **v4** существует официальная библиотека [amoCRM API Library](https://github.com/amocrm/amocrm-api-php).
3. Думаю причина в том, что в API **v2** код ответа НТТР `201` означал ошибку (посмотрите в официальной документации [коды ошибок](https://htmlpreview.github.io/?https://github.com/andrey-tech/amocrm-api-v2-docs/blob/master/docs/errors.html)), а API **v4** - это успешный ответ. Попробуйте добавить код `201` в `AmoAPI::$successStatusCodes`, но это, конечно, "костыли".

**Comment by instocky** [comment]
Здравствуйте, 
```
    /**
     * Коды состояния НТТР, соответствующие успешному выполнению запроса
     * @var array
     */
    public static $successStatusCodes = [ 200, 201, 202, 204 ];
```
**спасибо** добавил в массив - теперь это не считается ошибкой). 
**ps** Я смотрел официальную библиотеку. Ваша понравилась больше, в том числе и работой с oath2
