### ISSUE TITLE
AccessToken Oauth 2.0

### ISSUE THREAD

**Issue by instocky** [andrey-tech/amocrm-api-php#18]
Здравствуйте, 
```
use AmoCRM\{AmoAPI, AmoAPIException};
use AmoCRM\TokenStorage\TokenStorageException;

try {

    // Последующие авторизации
    $subdomain = 'testsubdomain';
    AmoAPI::oAuth2($subdomain);

   // Какой-то исполняемый код с обращением к AmoCRM

} catch (AmoAPIException $e) {
    printf('Ошибка авторизации (%d): %s' . PHP_EOL, $e->getCode(), $e->getMessage());
} catch (TokenStorageException $e) {
    printf('Ошибка обработки токенов (%d): %s' . PHP_EOL, $e->getCode(), $e->getMessage());
}
```

1.  уточните пжл, правильно понимаю - если токен "просрочен", то 401 ответ здесь заставит сработать CATCH и одновременно обновит testsubdomain.amocrm.json?
2. токен "живет" - **сутки**? Как можно **увеличить** время жизни?

**Comment by andrey-tech** [comment]
Здравствуйте!

1) Если токен просрочен, то код ответа НTTP `401` будет обработан внутри библиотеки и произойдёт обновление `testsubdomain.amocrm.json`, поэтому `catch` из примера не сработает.
2) Время жизни токена устанавливает amoCRM и его нельзя увеличить.

**Comment by instocky** [comment]
> 1. Если токен просрочен, то код ответа НTTP `401` будет обработан внутри библиотеки и произойдёт обновление `testsubdomain.amocrm.json`, поэтому `catch` из примера не сработает.

`} catch (AmoAPIException $e) {` если этот блок не сработает, то как же не "потерять" запрос из амо / или я неправильно понял Ваш ответ?

спасибо

**Comment by andrey-tech** [comment]
Вам не нужно беспокоиться об обработке кода ответа НТТР `401`. После обновления токена запрос в amoCRM будет отправлен вновь автоматически.

**Comment by instocky** [comment]
спасибо
