### ISSUE TITLE
Добавить теги и примечание в неразобранное

### ISSUE THREAD

**Issue by webparadoxer** [andrey-tech/amocrm-api-php#19]
Подскажите, как добавить теги и примечание в неразобранное?!

**Comment by webparadoxer** [comment]
$lead1->addTags(['#form', '#geo']);
теги привязываются через сделку, до связывания.
А вот с note проблема, не получается

**Comment by andrey-tech** [comment]
Добрый день!

Никак, ибо неразобранное ущербно, по крайней мере в API v2.

Из официальной документации amoCRM:
> Изначально неразобранное было в отдельном хранилище и являлось отдельной сущностью именно поэтому до сих пор в интерфейсах amoCRM и в API есть особенности которые отличают поведение сделки в статусе Неразобранное от сделок в других статусах.

**Comment by andrey-tech** [comment]
В отсутствии, в разумное время, обратной связи, закрываю данный issue.
