### ISSUE TITLE
Как авторизоваться первый раз?

### ISSUE THREAD

**Issue by Nurik985** [andrey-tech/amocrm-api-php#2]
Здравствуйте как авторизоваться первый раз если у меня нет authCode ?

**Comment by andrey-tech** [comment]
Здравствуйте!
Код авторизации (authCode) можно получить в настройках интеграции в разделе "ключи и доступы" вместе с ID интеграции и секретом интеграции.

**Comment by Nurik985** [comment]
это понятно но там пишет 20 минут и все у меня срок истек

**Comment by andrey-tech** [comment]
Опишите подробнее в чем проблема.
Вам необходимо лишь вызвать метод oAuth2() в течение 20 минут после получения кода авторизации.

**Comment by Nurik985** [comment]
да но сейчас уже 20 минут прошел надо пересоздать виджет?

**Comment by andrey-tech** [comment]
Каждый раз, когда в настройках интеграции отрывается раздел "ключи и доступы", создается новый код авторизации.

**Comment by Nurik985** [comment]
теперь понял спасибо

**Comment by Nurik985** [comment]
сейчас получаю такую ошибку что делаю не правильно?
http://joxi.ru/1A5Rv88IDRdgdr

**Comment by andrey-tech** [comment]
Код авторизации нужно передавать в метод oAuth2() только первый раз, чтобы обменять этот код на токены.
При последующих запросах в метод oAuth2() код авторизаци передавать не нужно.

**Comment by Nurik985** [comment]
извините что назойливо смотрите я сейчас один обратился чтобы обменять код на токен потом меняю код на это
http://joxi.ru/5mdG5DDC3Owxqr и смотрю и мне пишет это http://joxi.ru/Q2KjGwwhLoKzXm

**Comment by randomSymbol** [comment]
> извините что назойливо смотрите я сейчас один обратился чтобы обменять код на токен потом меняю код на это
> http://joxi.ru/5mdG5DDC3Owxqr и смотрю и мне пишет это http://joxi.ru/Q2KjGwwhLoKzXm

по всей видимости ключи истекли раньше чем ты получил токен потому в хранилище с ключами нет твоего аккаунта, пройди по пути 'путь до папки с сайтами или скриптом '\vendor\andrey-tech\amocrm-api-php\src\AmoCRM\TokenStorage\tokens и посмотри есть ли вообще файл и что в нем лежит

**Comment by Nurik985** [comment]
там не было файла потом пошел в amo открыл виджет поставил код и запустил скрипт сейчас все получился и появился json файл по вашему адресу Спасибо вам

**Comment by randomSymbol** [comment]
> там не было файла потом пошел в amo открыл виджет поставил код и запустил скрипт сейчас все получился и появился json файл по вашему адресу Спасибо вам

всегда рад помочь:)

**Comment by andrey-tech** [comment]
спасибо за помощь ;)
