### ISSUE TITLE
Определить первичную авторизацию.

### ISSUE THREAD

**Issue by evgeniyefimchenko** [andrey-tech/amocrm-api-php#4]
Доброго дня. Отличное легковесное решение для API AMO!

Как возможно программно определить что первичная авторизация уже происходила?

Пытался определить классом, но ответ всегда false. Кусок работающего кода:
`		// Первичная авторизация
		//AmoAPI::oAuth2($subdomain, $clientId, $clientSecret, $redirectUri, $authCode);
		
                // Вторичная авторизация
		AmoAPI::oAuth2($subdomain);

		// Получение информации об аккаунте
		$res = var_export(AmoAPI::getAccount(), true) . '<br/>';`

**Comment by andrey-tech** [comment]
Добрый день!

Воспользуйтесь методом hasTokens() класса FileStorage. 
Если первичная авторизация для нужного домена уже происходила, 
то в хранилище токенов будут токены для этого домена.

```php
$domain=AmoAPI::getAmoDomain($subdomain='testsubdomain');
$isTokensExist = AmoAPI::$tokenStorage->hasTokens($domain);
```

**Comment by evgeniyefimchenko** [comment]
К сожалению получаю вот такую ошибку PHP Fatal error:  Uncaught Error: Call to a member function hasTokens() on null in

**Comment by andrey-tech** [comment]
Немного поправил ваш код:

```php
use AmoCRM\{AmoAPI, AmoLead, AmoAPIException, AmoContact};
use AmoCRM\TokenStorage\{FileStorage, TokenStorageException};

function isFirstAuth() {
    $subdomain = 'testsubdomain';
    $domain = AmoAPI::getAmoDomain($subdomain);
    $tokenStorage = new FileStorage();
    return !$tokenStorage->hasTokens($domain);
}

function blabla() {
    if (isFirstAuth()) { // Первичная авторизация
        AmoAPI::oAuth2($subdomain, $clientId, $clientSecret, $redirect_uri, $authCode);
    } else { // Вторичная авторизация
        AmoAPI::oAuth2($subdomain);
    }
}
```

**Comment by evgeniyefimchenko** [comment]
Спасибо огромное!

**Comment by andrey-tech** [comment]
В названии вашей функции isFirstAuth() ставится вопрос "Это первичная авторизация?", поэтому она должна возвращать: true - первичная авторизация, false - вторичная. Метод hasTokens() возвратит true, если есть токены, то есть авторизация вторичная, поэтому тут требуется логическое отрицание.

**Comment by evgeniyefimchenko** [comment]
Спасибо!
