### ISSUE TITLE
Класс работы с пользователями

### ISSUE THREAD

**Issue by evgeniyefimchenko** [andrey-tech/amocrm-api-php#5]
Доброго дня.
Крайне не хватает методов для работы с пользователями. Хотя бы получения сведений(id, name) для назначения ответственного по сделке. (/api/v4/users)

Пытался сам расширить функционал, но ....

Добавил класс **AmoUser** по аналогии с другими. И дописал(копи-паст)  функцию **getAllUsers** в **AmoAPIGetAllEntities**

Но видимо плохо понимаю структуру проекта.

**Comment by andrey-tech** [comment]
1) Данная библиотека работает с AMO API v2, где нет отдельных методов для работы с пользователями.
2) Метод getAccount() с дополнительными параметрами позволяет получить всех пользователей. См. документацию.
