### ISSUE TITLE
Получить кастомные поля сущности

### ISSUE THREAD

**Issue by evgeniyefimchenko** [andrey-tech/amocrm-api-php#6]
Доброго дня.
А как можно получить все кастомные поля сущности ID, название и тд. К примеру сделки.
Заранее спасибо!

**Comment by andrey-tech** [comment]
Все дополнительные поля сущности, которые были получены от amoCRM API, находятся в публичном свойстве объекта сущности с именем `custom_fields`.

**Comment by evgeniyefimchenko** [comment]
То есть, что б создать сделку с доп. полями определёнными, нужно сначала получить любую сделку вытащить нужные ID полей и потом уже создавать. Всё просто! Спасибо.
