### ISSUE TITLE
getAll

### ISSUE THREAD

**Issue by zhalil** [andrey-tech/amocrm-api-php#7]
приветствую! не очень понятно как работает static getAll<Entities> (array $params, bool $returnResponse = false, string $subdomain = null) при попытке вывести сам генератор он оказывается пустым но если попробовать вывести через foreach все ок, так же вопрос как фильтровать к примеру по этапам? если забить в качестве параметров 'status_id'=>'id статуса' отдает просто все сделки

**Comment by zhalil** [comment]
по статусу вопрос отпал нужно было просто передать 'status' вместо 'status_id'

**Comment by andrey-tech** [comment]
Добрый день!

```php
    $generator = AmoAPI::getAllLeads([
        'status' => 142
    ]);
    foreach ($generator as $items) {
        foreach ($items as $item) {
            print_r($item);
        }
    }
```
