### ISSUE TITLE
Данные amoCRM

### ISSUE THREAD

**Issue by varimo** [andrey-tech/amocrm-api-php#9]
Как можно вывести все даннные amoCRM (id всех полей, всех контактов, сделок и тд)?

**Comment by andrey-tech** [comment]
Например, список ID всех контактов:
```php
$generator = AmoAPI::getAllContacts();
foreach ($generator as $contacts) {
    foreach ($contacts as $contact) {
        print_r($item->id);
    }
}
```

**Comment by varimo** [comment]
Выводит пустой экран, хотя там есть контакты

**Comment by varimo** [comment]
Разобрался. Спасибо

**Comment by varimo** [comment]
всё равно пуской экран выводит

**Comment by varimo** [comment]
$generator тоже пустой

**Comment by varimo** [comment]
Fatal error: Uncaught Error: Undefined constant "AmoCRM\CURL_SSLVERSION_TLSv1_2" in /var/www/varim694/data/www/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIRequest.php:257 Stack trace: #0 /var/www/varim694/data/www/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIRequest.php(319): AmoCRM\AmoAPI::setDefaultCurlOptions(Object(CurlHandle), 'shid98') #1 /var/www/varim694/data/www/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIOAuth2.php(147): AmoCRM\AmoAPI::request('/oauth2/access_...', 'POST', Array, 'shid98') #2 /var/www/varim694/data/www/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIOAuth2.php(82): AmoCRM\AmoAPI::getTokens('shid98') #3 /var/www/varim694/data/www/varimo.ru/send-crm.php(38): AmoCRM\AmoAPI::oAuth2('shid98', '1a24a5e8-8d13-4...', '2HIImy96N3cyMCp...', 'http://varimo.r...', 'def5020064f26ae...') #4 {main} thrown in /var/www/varim694/data/www/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIRequest.php on line 257

**Comment by andrey-tech** [comment]
1) Какая версия PHP установлена?
2) Какая версия библиотеки cURL используется?

**Comment by varimo** [comment]
PHP версии 8.0.9
cURL версии 7.29.0

**Comment by andrey-tech** [comment]
Требуется cURL >= 7.34.0.
Не понятно сочетание cURL 7.29 c PHP 8, если уже с PHP 7.4 идет cURL 7.69.

**Comment by varimo** [comment]
Обновил cURL. Ошибка пропала, но появилась другая ошибка. Вставлял код, который выше: 
$generator = AmoAPI::getAllContacts();
foreach ($generator as $contacts) {
    foreach ($contacts as $contact) {
        print_r($item->id);
    }
}

Теперь ошибка другая:
Fatal error: Uncaught TypeError: Argument 3 passed to AmoCRM\AmoAPI::getAll() must be of the type bool, null given, called in /var/home/s89629/public_html/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIGetAllEntities.php on line 74 and defined in /var/home/s89629/public_html/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIGetAllEntities.php:115 Stack trace: #0 /var/home/s89629/public_html/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIGetAllEntities.php(74): AmoCRM\AmoAPI::getAll('/api/v2/contact...', Array, NULL, false) #1 /var/home/s89629/public_html/varimo.ru/send-crm.php(43): AmoCRM\AmoAPI::getAllContacts() #2 {main} thrown in /var/home/s89629/public_html/varimo.ru/vendor/andrey-tech/amocrm-api-php/src/AmoCRM/AmoAPIGetAllEntities.php on line 115

**Comment by varimo** [comment]
Нашел ошибку. Подгружатся старая версия либы, где в функции getAll() параметры местами поменены. Надо было с githuh скачать папку src и вставить ее отдельно

**Comment by andrey-tech** [comment]
Проще использовать composer, чтобы избежать таких проблем.

**Comment by varimo** [comment]
Есть ли у getAllContacts() фильтрация не по основным полям (id контакта, имя), а по кастомным полям? Если да, то как сделать? Не смог разобраться

**Comment by varimo** [comment]
А точнее по конкретному значению определенного кастомного поля (например, определенный номер телефона)

**Comment by andrey-tech** [comment]
Воспользуйтесь поисковым запросом по всем заполненным полям сущности и отфильтруйте полученные результаты по значению нужного поля, например, телефона. Подробности запроса в [офф. документации](https://htmlpreview.github.io/?https://github.com/andrey-tech/amocrm-api-v2-docs/blob/master/docs/contacts.html).
```php
$response = AmoAPI::getContacts([ 'query' => $phone ]);
if (! is_null($response)) {
    foreach ($contacts as $contact) {
    ...
    }
}
```

**Comment by varimo** [comment]
Возможно ли в 'query' вставить сразу два параметра? Если хотя бы один из параметром есть, то выводил

**Comment by andrey-tech** [comment]
Согласно [офф. документации](https://htmlpreview.github.io/?https://github.com/andrey-tech/amocrm-api-v2-docs/blob/master/docs/contacts.html) в AmoCRM API v2 такой возможности нет.
